package hu.fitforfun.exception;

public enum ErrorCode {
    USER_NOT_EXISTS,
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,

    SPORT_FACILITY_ALREADY_EXISTS,
    SPORT_FACILITY_NOT_EXISTS,
    SPORT_FACILITY_ALREADY_RATED,

    INSTRUCTOR_NOT_EXISTS,
    INSTRUCTOR_ALREADY_RATED,

    SPORT_TYPE_ALREADY_EXISTS,

    EXERCISE_NOT_EXISTS,
    EXERCISE_ALREADY_EXISTS,

    SESSION_TIME_ALREADY_OCCUPIED,
    TRAINING_SESSION_NOT_EXISTS,
}
