package hu.fitforfun.exception;

public enum ErrorCode {
    USER_NOT_EXISTS,
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,

    SPORT_FACILITY_ALREADY_EXISTS,
    SPORT_FACILITY_NOT_EXISTS,
    SPORT_FACILITY_ALREADY_RATED,

    INSTRUCTOR_NOT_EXIST,
    INSTRUCTOR_ALREADY_RATED,

}
