spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
# jpa:
#    properties:
#      hibernate:
#        format_sql: true
  #logging:
    #  level:
      #org:
#      hibernate:
#        SQL: debug
      #type:
      # descriptor:
    #   sql: trace