spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:~/fitforfundb

logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace